name: Simple Ubuntu Workflow

on:
  push:
    branches:
      - main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "👋 Hello from GitHub Actions on Ubuntu"
